import 'package:flutter/material.dart';

class AboutPage extends StatelessWidget {
  const AboutPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("About"),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(15.0),
        child: Text('''
      Quigo is a minor project submitted by Gaurav Jaiswar (216320016) and Mayank Pratap Singh (216320026) at Fet, Gurukul Kangri (Deemed to be University) 

      The app is developed using Flutter with Firebase as a backend

References / Asset Sources:-
- Animation on homepage card => lottiefiles.com
- Quiz Icons => flaticons.com
- Profile avatars => freepik.com


All the quizes included in the app are generated by chatgpt.com

      ''', textAlign: TextAlign.justify, style: TextStyle(fontSize: 15)),
      ),
    );
  }
}
