// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDR8dDq0k7LNdwroPzqMMfe8NoVqbZ4Q',
    appId: '1:187149671800:web:6f6554408dd2a8a9f57c8d',
    messagingSenderId: '187149671800',
    projectId: 'quiz-99304',
    authDomain: 'quiz-99304.firebaseapp.com',
    storageBucket: 'quiz-99304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxj7BmZr_UpK1MiXZYhQbgl3x0lkj5tmE',
    appId: '1:187149671800:ios:ead51a3dfc4b8792f57c8d',
    messagingSenderId: '187149671800',
    projectId: 'quiz-99304',
    storageBucket: 'quiz-99304.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxj7BmZr_UpK1MiXZYhQbgl3x0lkj5tmE',
    appId: '1:187149671800:ios:ead51a3dfc4b8792f57c8d',
    messagingSenderId: '187149671800',
    projectId: 'quiz-99304',
    storageBucket: 'quiz-99304.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlDR8dDq0k7LNdwroPzqMMfe8NoVqbZ4Q',
    appId: '1:187149671800:web:cad65eb909e813a8f57c8d',
    messagingSenderId: '187149671800',
    projectId: 'quiz-99304',
    authDomain: 'quiz-99304.firebaseapp.com',
    storageBucket: 'quiz-99304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDlkwWhu_DEaw6vvPr3tbcZBOEOArWrM',
    appId: '1:187149671800:android:e0994afbd0deaf8df57c8d',
    messagingSenderId: '187149671800',
    projectId: 'quiz-99304',
    storageBucket: 'quiz-99304.appspot.com',
  );

}